# Empirical Measurement Challenges {#intro}

The research questions asked in this report are related to the [Music Creator Earnings' Project](https://www.gov.uk/government/publications/music-creators-earnings-in-the-digital-era) (MCE), exploring issues concerning equitable remuneration and earnings distributions. We were tasked with providing a longitudinal analysis of earnings development and relating our findings to equitable remuneration. The starting point of our work was centred around a very broadly defined problem: how much money music creators (rightsholders) earn from streaming, how these earnings are distributed, and how the earnings and their distribution have developed during the last decade.

```{r packages, include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'ggplot2', 'scales', 'dplyr', 'tidyr', 'tidyverse',  'ggplot2','stats', 'purrr', 'kableExtra', 'webshot' ), 'packages.bib')
```

The highly globalized music industry generates two important international reports, as well as several national reports, but these are not suitable for the analysis of the typical or average rightsholder, nor for small labels and publishers who do not represent a large and internationally diversified portfolio of music works or recordings. Copyright and neighboring right revenues are collected in national jurisdictions. Because British artists are almost never constrained by their use of language, and the UK Music Industry is highly competitive in the global music markets, even relatively less known rightsholders earn revenues from dozens of national markets. The lack of market information on music sales volumes, prices for each jurisdiction, and the unaccounted for national, domestic, and foreign revenues makes the analysis of the rightholder’s earnings, or the economics of a certain distribution channel like music streaming or media platforms, impossible.

While total earnings are reported by international and national organizations, they hide five important economic variables: changes in sales volumes, changes in prices, market share on various national jurisdictions (which have their own volume and price movements), the exchange rates applied, and the share of the repertoire exploited. Even worse, the global music industry has no comprehensive database of rightsholders, music works, and recordings. Many rights are represented by heirs or passive investors. And because of the enormous number of works and recordings, in any given royalty payment period, most works/recordings are not used and not compensated. The lack of a known population and distribution makes usual indicators as average or median earnings arithmetically impossible to compute, and the large number of disused works and recordings makes even the estimation of the typical (median) value useless for economic analysis. The estimation of the arithmetic mean is equally problematic, because it is distorted by the earnings of very few global stars. To understand the streaming economy from the perspective of a typical or average rightsholder, or from the perspective of a small independent label or music publisher, requires very challenging sampling techniques either in surveying or in empirically observing and aggregating data from royalty accounts. National and international music organizations are not equipped with the data processing and statistical capacity to do so.

This is the problem that the Digital Music Observatory, a working demo of the European Music Observatory is solving. It grew out of the Central & Eastern European Music Industry Databases (CEEMID) initiative in 2014, in which righthsolders from three countries attempted to solve this problem. By 2019, CEEMID had collected information on 20 European markets, including the United Kingdom, and processed data on far more markets. The state51 music group, through its distribution arm, has been supporting the creation of the largest ever European market report, the Central European Market Report, and supported the creation of the CEEMID-CI indexes, which, for the first time provided a stock-index type of view from an individual rightsholder’s perspective on volume and price movements in the UK and in other countries. The state51 music group drew attention to the observatory approach and this work in the Digital, Culture, Media and Sport Committee (DCMS) Select Committee of the British House of Commons. The MCE project first individually contacted the Digital Music Observatory (successor of CEEMID) and state51, and eventually with the permission of state51, the project commissioned this report, which re-uses the CEEMID-CI indexes. The MCE project also committed to share data in the Digital Music Observatory.

The first chapter is divided into four subchapters: 

- \@ref(market-definition) introduces the considerations for defining the relevant product/service market after the consideration of the entire value chain of the music industry and the various problems related to defining the relevant market in terms of a national or global music market.
- \@ref(estimating-volumes) introduces the problems of estimating the most basic economic variable, the quantity or volume of the music used in the market. 
- Most publicly available information on music neither contains volumes or prices, we will investigate the possibility of observing or estimating prices in \@ref(estimating-prices). We show that because of the highly globalized nature of the music industry, a very careful attention must be paid to understanding the [functional currency](#functional-currency) used by entities in the market to report revenues (See \@ref(functional-currency)).
- \@ref(estimation-strategies) then overviews the potential empirical data sources and empirical [estimation strategies](#estimation-strategies) for obtaining quantity and price information for the relevant product/service market, from a relevant geographical segment, for an evidence-based market analysis.

The \@ref(price-valuation) [Price Harmonization and Valuation](#price-valuation) chapter deals with the price setting standards of the music industry, and the difficulties of price comparison in the various licensing modes of the industry. We first introduce the regulatory framework of price setting in the music industry. In \@ref(fair-value) [Fair Value](#fair-value) we argue that from an economic point of view, the IFRS and WIPO standards on the fair valuation of intangible assets, including copyrights and neighboring rights, are practically more important for a market analysis, then the issue of [equitable remuneration](#equitable-remuneration)---and we believe that in the policy debate often these terms are used in confusion. Then we introduce the problems of value transfer to [unlicensed platforms](#unlicensed) and we make the case that music streaming and UUC should not be treated as one market segment. 

#functional-currency

The third chapter, using computer simulations, gives a fuller picture. It shows that in the UK and many other markets, in the period of 2016-2019, the growth of streaming use hardly offset the diminishing price (value) of the streams. In many markets, rightsholders, expressed in British pounds, experienced flat earnings, which was by a large extent due to the benevolent USD/GBP, EUR/GBP, and CHF/GBP exchange rates. It is likely that the majority of individual rightsholders experienced flat or diminishing revenues, and later releases brought less and less revenue per a thousand streams. A less benevolent exchange rate environment could have brought very large losses of revenue (See \@ref(exchange-rate-effects) for more details.)

Our computer simulations show that British rightsholders are experiencing a rather varied picture of music streaming. Because of the generally falling value of streams, short-lived hits are more impacted by value decline than perennial hits (See subchapters \@ref(difference-popularity) and \@ref(release-time).) Rightsholders with a diversified international audience are partly shielded by these effects (See \@ref(difference-international).) Younger stars and new genres generally experience a windfall from the pro-rata distribution system and older artists with more conventional genres such as rock or blues are experiencing headwinds. The publicly available market totals are hiding completely different market experiences.

Our report highlights some important lessons. First, we show that in the era of global music sales platforms it is impossible to understand the economics of music streaming without international data harmonization and advanced surveying and sampling. Paradoxically, without careful adjustments for accruals, market shares in jurisdictions, and disaggregation of price and volume changes, the British industry cannot analyze its own economics because of its high level of integration to the global music economy. Furthermore, the replacement of former public performances, mechanical licensing, and private copying remunerations (which has been available for British rightsholders in their European markets for decades) with less valuable streaming licenses has left many rightsholders poorer. Making adjustments on the distribution system without modifying the definition of equitable remuneration rights or the pro-rata distribution scheme of streaming platforms opens up many conflicts while solving not enough fundamental problems.  Therefore, we suggest participation in international data harmonization and policy coordination to help regain the historical value of music.

It is impossible to understand music streaming earnings outside the context of the music market or the music business ecosystem. Music streaming royalty rates and distribution methods largely follow long-established practices and regulations concerning valuing intellectual property, accounting for royalties, and regulating the administration of copyrights and neighbouring rights. Music streaming competes with other uses, such as public performances in television and radio broadcasting, or digital downloads. Music streaming cannot be analysed in isolation from the volume and price trends of public performance, mechanical licensing, and home copying.

## Relevant market for analysis & the value chain {#relevant-market}

In competition policy, a relevant market is a market in which a particular product or service is sold---an intersection of a relevant product market and a relevant geographic market. This concept is particularly useful in our case, because music has no clear-cut product, service, or geographical market.

## Relevant product/service market {#intro-relevant-service}
A relevant product market comprises all those products and/or services which are regarded as interchangeable or substitutable by the consumer by reason of the products' characteristics, their prices and their intended use---experience and research in other countries shows that music streaming can be substituted with other, differently licensed music, for example, listening to music via the media platform YouTube, or from mp3 files. Even the sale of physical music products, such as microcasettes and CDs, can be substituted with music services such as streaming subscriptions. 

### Market geography
A relevant geographic market comprises the area in which the firms concerned are involved in the supply of products or services and in which the conditions of competition are sufficiently homogeneous.

While observing their global income is relatively easy, it tells us nothing about the economics of those earnings, i.e. the change of demand, supply, volumes, and prices. 
Aggregated income indicators are usually made in two versions: national or domestic.  The national music creators' earning is the earning of rightsholders who live or are registered as legal persons in the United Kingdom. The domestic income of the music industry is the earning made by entities in the United Kingdom, including the earnings of non-resident rightsholders they represent. Because in most industry sources, the domestic and the national approach is not clearly delienated, it is very challenging to carry out a proper data analysis.

The loss of information, as we will show in the next chapter, is critical, because volumes, prices and exchange rates move rather differently from the UK market in other countries, so it is very important to know if an entity in the UK is reporting its German royalties or not, and what exchange rate is used to report German revenues. This seemingly technical problem is of crucial importance when we deal with such a highly globalized industry as the music industry. We will introduce this as a problem of empirical data collection in \@ref(relevant-geographical-market) [Relevant geographical market](#relevant-geographical-market) and we will show a case study in \@ref(#simulation-results) [Price Disintegration: Timeframe and Functional Currency Problems](#simulation-results) to highlight the importance of this problem.

## Volumes {#intro-volumes}
Many people are familiar with the work of _Sixto Rodriguez_, a Detroit-born songwriter, whose works were not licensed for more than 30 years after they were recorded between 1967 and 1971, until 1997, when it was famously discovered that he is a best-selling songwriter in South Africa. After the documentary _Searching for Sugarman_ won the Academy Prize, his recordings, 40 years after their release, became golden and platinum records in many countries.

Many artists are active in their twenties, and in the 21st century they can expect to live 60-70 years longer, and their heirs enjoy copyright protection for further decades. Like Rodríguez's recordings, there may be many protected works and recordings that have not been observed in distribution schemes, media and streaming platforms, yet become successful in the future. In the absence of a global, compulsory registry of copyrights, we do not even know how many works and recordings enjoy copyright protection in 2021.

Because there is no global database of copyright (and neighbouring right) protected music works and recordings, we do not know precisely how many rightsholders and how many works or recordings are protected by the law. From a strict mathematical perspective the average (mean) and typical (median) rightsholder earnings do not exist, because their calculation would involve division by, or ranking of an unknown number of rightsholders.

### Sampling the unknown rightsholder population

Most rightsholders create works and recordings that have a limited lifespan: in a few years they lose their audience, and in the absence of their use, they no longer create income.  But, as the case of Sixto Rodríguez shows, they may in the future, even decades, or a hundred years later.  There are many rightsholders who create something, but never become full-time creators, or eventually they go back to part-time or occassional creators. Creating a representative survey of rightsholders is very challenging, becaues the rightsholder population has many inactive members.

Similarly to rightsholders, most of the works and recordings are not in use, or hardly in use at any given time period.  Creating a representative sample of recordings or works for empirical observation is very difficult, because we simply do not know how many works or recordings exist.

Since 2014, we perfected sampling both rightsholder populations and recordings to create better and better representations of the creators and their creations.  We created special surveys among music professionals to establish their typical earning levels and composition, and we created special samples of recordings to observe their typical revenues.

The way we sample or weigh musicians’ self-reported earnings in the Digital Music Observatory’s surveys is based on the known, but anonymised payouts of author’s societies, and comparing it to the self-reported earnings from author’s societies.  The closer the self-reported median, quartile, or average payouts get to the know, but anonymous true payouts, the better the sample. In Hungary and Slovakia we were able to create highly representative music professional surveys for the active musician population. On active musician population we meant those living artists, who recieve some collectively managed royalties in a given year, i.e., their works are played on radio, television, directly identified public performance, collectively managed streaming services, on concerts, or other uses where author’s societies record use and collect revenues. We believe that this is the best target population for investigating music creator’s earnings. This target population is usually rather different from the payrolls of author’s societies, not to mention neighboring rights soceities, becasue those contain heirs of many deceised artists. This target population does *not* include new artist who do not have yet a registered work or commercially released sound recording, or whose works are not exploited in these channels. Generally, this is an appropriate target, though in some genres they may not be representative.  (For example, old and classical musicians play music that has no author royalties, and some subgenres of hip-hop are not radio friendly and avoid any registration.)


## Prices

### Equitable remuneration {.unnumbered intro-equitable}

In the UK policy debate, a potential redefinition of equitable remuneration rights received noteworthy attention, and it is a good starting point to understand music earnings. Equitable remuneration is originally connected to a compulsory license that must be paid when recorded music is played on a publicly accessible location to the performing artists and music producers.


The current UK debate is perhaps too much focused on the UK definition of equitable remuneration rights. The changes promoted by the Broken Record campaign were successfully made in several European jurisdictions, but they did not significantly change the earnings of most creators. By focusing on the re-definition of the equitable remuneration right, the debate is only focused on the re-distribution of a very small portion of the music ecoystems’s income. This blurs the fact that the general level of earnings---which is not governed by the equitable remuneration right, but by fair value, arm’s length standard, and competition law---is declining and seems to be inadequate compared to historical levels.

### Fair value {.unnumbered #intro-fair-value}

When rightsholders are not in the position to negotiate rates freely, various legal, accounting, and economic norms, and institutional guarantees must be in place so that they receive fair and equitable remuneration. Because copyrights and neighbouring rights (in European parlance, or recording copyrights in U.S. terminology) are valuable intellectual property rights, they entail fair compensation for the use of rightsholders' works or recorded fixations.

When intellectual property is sold (against a lump-sum payment), or licensed (for periodical payment), or used as a pledge against a loan, the transaction must comply with the *Fair Value* standard.  This standard is, similarly to copyright law, set by international law, which generally can only in detail be modified by UK law. The Fair Value standard of the *International Financial Reporting Board* has been incorporated into UK law via EU law, and remained UK law after Brexit.

In 2008, the global recording industry body, IFPI, published _Valuing the use of recorded music_, created by Price Waterhouse Cooper [@pwc_valuing_2008]. This excellent methodological guide applies the WIPO and IFRS standards [@ifrs_fair_value_2011; @flignor_orozco_ip_valuation_2006; @puca_intangible_2019] on valuing copyrights in more practical terms for the music industry. It is important to recognize that IFRS, like copyright law, is international law, and it can be enforced in the UK courts. The valuation principles are enshrined in the fair valuation principles of the WIPO, and the fair value principles of the International Financial Standards Board. While the *equitable remuneration right* may only apply, from a legal perspective to a subset of rights, the economic techniques of valuing copyrights, or any type of intellectual rights are similar. Therefore, even when no law or jurisprudence stipulates that remuneration must be equitable, the same economic valuation techniques should be used that we use for setting the remuneration level for *equitable remuneration*.

The recognized fair valuation principles stipulate that the “most applicable method” must be used in valuations. In the music industry, the use of the "cost approach" is completely impractical, which leaves open the choice between the “income approach” and the “market approach”.

### Value transfer {.unnumbered}

During the creation of this report a legislative process is underway to implement a new European legislation that aims to close the value transfer to unlicensed media platforms. Media platforms, like YouTube, unlike licensed music streaming services like Spotify, Deezer, Apple Music or licensed audiovisual services like Netflix, did not get a license from rightsholders for the use of their music, audiovisual content, literary or artworks. Their objections to such licenses were based on the safe harbor of copyright law mandated by the U.S. Congress to help the evolution of internet businesses. 

The representative associations of composers [@gesac_regulatory_2015; @gesac_copyright_2015; @cisac_cisac_2017], performers [@aepo-artis_give_2016; @aepo-artis_comments_2017], and producers [@moore_value_2016]  in Europe were all strongly calling for a change in these practices, while technology companies on the other side were vehemently lobbying European governments and members of the European Parliament to stop or water down proposals. Eventually the European Union adopted the new Copyright Directive  [@eu_directive_2019_790].  The transposition of this European directive into national copyright law is happening in these months all over Europe (or it has already finished.) It is yet to be seen if the regulatory approach will close the value gap in Europe, but it is likely that revenues from the United Kingdom will fall under a different copyright regulation.

Value transfer is undermining mechanical licensing, public performance, mixed streaming licenses, and even compensation values for home copying. They offer a cheaper platform for viewers than licensed onces, which moves the basis of potentially royalty earning revenues towards the media platform. We have measured this effect in several European countries, and we have found this to be far more significant than the potential redistribution effect from pro-rata streaming distribution (see the next \@ref(distribution-rules) subchapter) or the redefinition of the equitable remuneration right (subchapter \@ref(equitable-remuneration)). 

1. Unlicensed uses create competition to the business-to-business users of music, audiovisual content, books and other copyright protected content. For example, television stations and radio stations lost audiences to YouTube, because YouTube could offer programming "for free",  as it paid only about 1-10% of the similar royalties of broadcasters for content. This means that advertising revenue moved from TV and radio stations to YouTube. This revenue should have been shared with rightsholders by the broadcasters.

2. The availability of unlicensed platforms, such as YouTube, that claims not to be a streaming platform, and pirate websites reduced demand for licensed, legalized use of copyright protected content. The lower sales volumes and the direct loss of advertisement revenues reduced the market price of content.

3. Because private copying remuneration must be based on market values of music, filmed content, literary works, and other works, it is important that we enumerate the price loss due to illegal activities, so that the damage claim is truly based on arm's length rather than  illegal market transactions.

We were not provided with data to estimate the size of the value transfer in the United Kingdom, but given the global nature of the music ecosystem, we do not believe that the British rightsholders are affected differently than European ones. Partly, because a large part of the British revenues are export revenues to the European Union, and partly because unlicensed media platform are competing precisely in the same manner in the UK with licensed public performers or streaming platforms like in other countries. We believe that the existence of the value transfer is one of the sources of the declining value of music shown in subchapter \@ref(streaming-price), but we have not attempted to estimate the size of this effect. However, our detailed data in Hungary, Croatia, and Slovakia suggest that the value transfer amounts to 10-20% of the total music market value.

## Copyright Policy Issues

The MCE project is taking place in a time when serious policy changes and discussions are taking place in the United Kingdom and Europe. As the UK is building a new regulatory system, its legislation must decide on which aspects of the copyright regulation to keep from retained EU law and which aspects to change.

Because of the important global position of the UK music industry, the international policy debates and expected or undergoing changes are relevant for understanding the earnings prospects of music creators. We believe that the most important factors at play are the consolidation of the data management of a very fragmented music ecosystem, the creation of  trustworthy AI in algorithmic music sales and the closure of the value gap towards media platforms. These problems are directly related to the low level of earnings from music streaming, and some unjustified differences among rightsholders.

### Problems with copyright management

As we will show in the \@ref(simulation-results) [Differences in Music Creators' Earngins: Simulation Results](#simulation-results) chapter,
the fluctuation in streaming price and currency conversion to the function currency from the market of sale can cause much and justified earnings differences among British rightsholders. But there are differences which are not justified and related to some form of malfunction in the rights management system.

For producers and performers, the problems are partly different from the problems of composers, because streaming platforms license the copyrights and neighbouring rights (the publishing side and recording side) differently. But generally, both publishing and the recording side suffers from the problem of high documentation and data processing costs, high error rates, and large sums of unpaid revenues. The lack of data interoperability, frequent changes of standards, and the general fragmentation of the music ecosystem--which disallows the application of specialized documentation or data management workforce--causes delays or non-payment for rightsholders. In some markets, we observed that this could affect up to fifty percent of all rightsholders.

In the current market situation, with the current streaming prices and streaming volumes, the cost of proper (metadata) documentation of works and recordings often exceeds the value of expected future royalty cash flows. Because metadata documentation and data processing exhibit large economies of scale (i.e., the unit costs are much lower for a million songs than for a thousand songs, and the difference is even greater to a hundred songs), payment problems plague independent labels and publishers. In Europe, the publishing share in streaming revenues is unusually low compared to the recording side, therefore the proper documentation of composer royalties is particularly challenging.

Our [Digital Music Observatory](https://music.dataobservatory.eu/), and its related [Listen Local Initiative](https://reprex.nl/project/listen-local/) was partly set up to allow the pooling of data processing, documentation automation for smaller organizations, like independent labels, or national organizations of smaller countries, who usually manage a much smaller national catalogue than major music businesses. We are participating in an international research consortium (which includes the UK Copyright and. Creative Economy Centre from the United Kingdom) to understand the problems in data and metadata management and propose copyright law changes in Europe and the UK.

We do not have estimates about the scope of the problem in the UK, but in the United States, after the introduction of the new Music Modernization Act, the Mechanical Licensing Collective received in January 2021 $424.38 million in unmatched royalties from Apple Music, Amazon Music, and Spotify among other streaming services. According to various reports, these streaming services paid accrued historical unmatched royalties, often called “black box money,” to the MLC in order to get these royalties to copyright holders, songwriters, and publishers who have applied to become MLC members. Apple Music transferred the most money to the MLC with over \$163 million, while Spotify wasn’t far behindl submitting over \$152 million. Amazon, meanwhile, transferred \$42 million, while Google/YouTube sent \$32 million. We experienced similar problems with a smaller absolute and a higher relative value on the smaller European markets.

### Distribution rules {#distribution-rules}

Recently we have seen a considerable discussion around the choice between the *pro-rata* versus *user-centric* model of royalty distribution from streaming platforms. Except for SoundCloud, and only from April 2021, music streaming services do not divide up the royalty fund (from subscription and advertising revenues) based on the number of streams per recording. We did not have a mandate to analyze this issue deeper, but we believe that in the long-term, the choice between these two models is a false dichotomy, and the music industry must look beyond its boundaries, for example, to telecom services, to find a better and more just distribution system. We summarize empirical studies made in Denmark, Norway and France in subchapter \@ref(#earnings-distorsion).

### Trustworthy AI

Recommendation systems of music and media streaming platforms are extremely complex systems, and they operate as a proprietary marketplaces where the rules of fair competition, fair play, and equitable remuneration are basically maintained by the owner of the platform. Forthcoming UK and EU regulations try to make these autonomous or semi-autonomous algorithmic systems accountable. 

One important element of work we are doing with the founding partners of our Music Observatory--with the support of the Slovak Arts Council--is to find out why classical musicians are paid less, or why 15% of the Slovak, Estonian, Hungarian and Dutch artists never appear on anybody’s personalized recommendations [@antal_promoting_slovak_2020].  

When we analyze the effect of AI algorithms on royalty payments, we describe potentially bad outcomes of the use of automated sales or personalization, which undermines or contradicts national or EU-level cultural policy goals, national media regulation, national child protection rules, national or international fundamental rights protection against discrimination without basis. In a recommendation system many bad outcomes may happen that can eventually lead to lower or no payment for a rightsholder. 

In these cases, we are not talking about _unjustified_ differences of payment as simulated in \@ref(simulation-results) [Differences in Earnings: Simulation Results](#simulation-results), but a systematic breach of non-copyright rules that lead to an _unjustified_ lower streaming _volume_, and therefore a lower royalty payment on lower volumes. A recommendation system might exhibit the following characteristics:

- It may recommend too few female or small country artists, or start recommending artists with hateful language.
- It may put certain label's music on less visible places.
- It may make the works of major labels easier to find than those of independent labels.
- It may place less works and recordings on personalized lists than local content guidelines (applied in about 90 territories of the world, see [@stein_quotas_2012]) would require from competing local television or radio stations.
- Your personalized list is filled with misleading track/artists names that are hunting for accidental streams, much like click-hunting text content that plays search engines.

These *potential* undesireable outcomes are sometimes illegal, and, for example, they may hypothetically make Welsh artists earn significantly less than American or English artists. 

In our work in Slovakia, we reverse engineered some of these undesirable outcomes and we are planning similar research in the United Kingdom. We do not have relevant empirical estimates for the United Kingdom, however, and our experience shows that one potential reason why UK rightsholders are facing such a different outlook on streaming revenues may be due to various bad outcomes of the largely autonomous system of playlist personalization and playlist curation. We want to stress that these problems are unlikely to be the results of foul play by streaming providers, but they are inherent to extremely complex systems that need constant and complicated monitoring.
